"""initial schema

Revision ID: 4a8a521c3a30
Revises: 
Create Date: 2026-06-02 17:59:36.275446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8a521c3a30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('categories_parent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_index(op.f('categories_slug_idx'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('orders_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('brand_logo', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('products_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('products_slug_idx'), 'products', ['slug'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey'))
    )
    op.create_index(op.f('user_sessions_id_idx'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('user_sessions_token_idx'), 'user_sessions', ['token'], unique=True)
    op.create_table('product_colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_colors_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_colors_pkey'))
    )
    op.create_table('product_sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=50), nullable=False),
    sa.Column('chest_cm', sa.String(length=50), nullable=True),
    sa.Column('waist_cm', sa.String(length=50), nullable=True),
    sa.Column('hips_cm', sa.String(length=50), nullable=True),
    sa.Column('label_size', sa.String(length=50), nullable=True),
    sa.Column('height_cm', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_sizes_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_sizes_pkey'))
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['product_colors.id'], name=op.f('product_variants_color_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_variants_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['product_sizes.id'], name=op.f('product_variants_size_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_variants_pkey')),
    sa.UniqueConstraint('sku', name=op.f('product_variants_sku_key'))
    )
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cart_items_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('cart_items_variant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_items_pkey')),
    sa.UniqueConstraint('session_id', 'variant_id', name='uq_cart_session_variant'),
    sa.UniqueConstraint('user_id', 'variant_id', name='uq_cart_user_variant')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('order_items_variant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
    )
    op.create_table('tryon_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('person_image_url', sa.String(length=500), nullable=False),
    sa.Column('garment_image_url', sa.String(length=500), nullable=False),
    sa.Column('mask_image_url', sa.String(length=500), nullable=True),
    sa.Column('result_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tryon_sessions_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('tryon_sessions_variant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tryon_sessions_pkey'))
    )
    op.create_table('wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wishlists_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('wishlists_variant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wishlists_pkey')),
    sa.UniqueConstraint('session_id', 'variant_id', name='unique_session_wishlist', postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('user_id', 'variant_id', name='unique_user_wishlist', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('wishlists_session_id_idx'), 'wishlists', ['session_id'], unique=False)
    op.create_index(op.f('wishlists_user_id_idx'), 'wishlists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('wishlists_user_id_idx'), table_name='wishlists')
    op.drop_index(op.f('wishlists_session_id_idx'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_table('tryon_sessions')
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('product_variants')
    op.drop_table('product_sizes')
    op.drop_table('product_colors')
    op.drop_index(op.f('user_sessions_token_idx'), table_name='user_sessions')
    op.drop_index(op.f('user_sessions_id_idx'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('products_slug_idx'), table_name='products')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('categories_slug_idx'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
